---
title: "Practical Data Analysis Homework 4"
author: "Christopher Costello"
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  fig.path = "my_report_files/"
  )
```


# Question 2

How many rows are available in the Measurements table of the Smith College Wideband Auditory Immittance database?

```{r question 2}
library(tidyverse)
library(RMariaDB)
con <- dbConnect(
  MariaDB(), host = "scidb.smith.edu",
  user = "waiuser", password = "smith_waiDB", 
  dbname = "wai"
)
Measurements <- tbl(con, "Measurements")

dbGetQuery(con,
           "
           SELECT SUM(1) AS num_rows
           FROM `Measurements`
           ")
```

From this query, we find that the number of rows in the Measurements table is 5,052,304.

# Question 3

Identify what years of data are available in the flights table of the airlines database.

```{r question 3}
library(tidyverse)
library(mdsr)
library(RMariaDB)
con <- dbConnect_scidb("airlines")

dbListTables(con)

tbl(con, "flights")

dbGetQuery(con,
           "
           SELECT DISTINCT year
           FROM flights
           ")
```